### PR TITLE
Fixes shard drop on collection creation

### LINKED ISSUE #379: Panic if collection create operation fails
If there are some problems with creation of the collection

https://github.com/qdrant/qdrant/blob/8a2c17f0d4c48933670cc62b07ed81024f7ef9dd/lib/collection/src/lib.rs#L60

and operation fails with `Err(....)?` - already loaded shards are dropped without proper `before_drop` call.

What can be done about it:

- Add explicit check of `before_drop` flag in `Drop` function of shards to make further possible debug easier.
- Implement custom error handling in `Collection::new`, so that `before_drop` is called in case of error
- Lower the amount of shards/segments in `lib/collection/tests/collection_restore_test.rs`, so it could be run with default `Maximum number of open file descriptors` on Ubuntu (`ulimit -n 1024`)

Additionally:

Make

``` rust
pub async fn before_drop(&mut self) {
    for (_, mut shard) in self.shards.drain() {
        shard.before_drop().await
    }
    self.before_drop_called = true
}
```
parallel

### PR DESCRIPTION
**Pull request by e-ivkov**
1. Fixes shard drop on collection creation (Closes #379 )
2. Fixes collection info method - 
previously info method could count same segment's info twice.
3. Concurrent waiting for the shard drop
4. Decreased number of shards per collection in tests to 3, number of segments to 2

### CODE REVIEW

File: lib/collection/src/lib.rs [hunk 1]
```diff
@@ -57,23 +58,31 @@ pub struct Collection {
...
     ) -> Result<Self, CollectionError> {
         config.save(path)?;
         let mut ring = HashRing::new();
-        let mut shards = HashMap::new();
+        let mut shards: HashMap<ShardId, Shard> = HashMap::new();
         for shard_id in 0..config.params.shard_number {
             let shard_path = shard_path(path, shard_id);
             create_dir_all(&shard_path).map_err(|err| CollectionError::ServiceError {
                 error: format!("Can't create shard {shard_id} directory. Error: {}", err),
             })?;
```
Comment (generall) [inline lib/collection/src/lib.rs:73]: This part could also fail with error

Comment (e-ivkov) [reply lib/collection/src/lib.rs:73]: Thanks!

**Review by generall — APPROVED** [review]

File: lib/collection/src/lib.rs [hunk 2]
```diff
@@ -383,9 +394,12 @@ impl Collection {
     }
 
     pub async fn before_drop(&mut self) {
-        for (_, mut shard) in self.shards.drain() {
-            shard.before_drop().await
-        }
+        let futures: FuturesUnordered<_> = self
```
Comment (agourlay) [inline lib/collection/src/lib.rs:397]: nitpick: Depending on the number of shards, this could generates a lot of concurrent work.

In general I prefer to bound the number of in-flight item to not exhaust resources.
Is it possible to do this here? e.g. have at most 3 concurrents `before_drop`.

You can also discard this comment if you think that this not a real issue for a production load :factory:

Comment (agourlay) [reply lib/collection/src/lib.rs:397]: I trust you on this one :+1:

**Review by agourlay — APPROVED** [review]
