### PR TITLE
fix(segment): guard min_should estimator edge cases

### LINKED ISSUE #7974: Query Issue 1.16.3 Server
## Current Behavior
2026-01-23T00:40:57.337129Z ERROR qdrant::startup: Panic occurred in file library/alloc/src/raw_vec/mod.rs at line 28: capacity overflow

2026-01-23T00:40:57.337218Z ERROR qdrant::startup: Panic backtrace:

   0: qdrant::startup::setup_panic_hook::{{closure}}

   1: std::panicking::panic_with_hook

   2: std::panicking::panic_handler::{{closure}}

   3: std::sys::backtrace::__rust_end_short_backtrace

   4: __rustc::rust_begin_unwind

   5: core::panicking::panic_fmt

   6: alloc::raw_vec::capacity_overflow

   7: alloc::raw_vec::handle_error

   8: segment::index::query_estimator::combine_min_should_estimations

   9: segment::index::query_estimator::estimate_filter

  10: segment::index::query_estimator::estimate_filter

  11: segment::index::query_estimator::estimate_filter

  12: <segment::index::struct_payload_index::StructPayloadIndex as segment::index::payload_index_base::PayloadIndex>::estimate_cardinality

  13: <segment::index::vector_index_base::VectorIndexEnum as segment::index::vector_index_base::VectorIndex>::search

  14: segment::segment::entry::<impl segment::entry::entry_point::SegmentEntry for segment::segment::Segment>::search_batch

  15: collection::collection_manager::segments_searcher::execute_batch_search

  16: collection::collection_manager::segments_searcher::search_in_segment

  17: tokio::runtime::task::raw::poll

  18: std::sys::backtrace::__rust_begin_short_backtrace

  19: core::ops::function::FnOnce::call_once{{vtable.shim}}

  20: std::sys::thread::unix::Thread::new::thread_start

  21: <unknown>

  22: <unknown>

 

2026-01-23T00:40:57.337242Z ERROR qdrant::startup: Panic occurred in file library/alloc/src/raw_vec/mod.rs at line 28: capacity overflow

2026-01-23T00:40:57.340758Z DEBUG collection::shards::replica_set::execute_read_operation: Read operation failed: Service internal error: Internal error: status: Internal, message: "Service internal error: task 1959637 panicked with message \"capacity overflow\"", details: [], metadata: MetadataMap { headers: {"content-type": "application/grpc", "date": "Fri, 23 Jan 2026 00:40:56 GMT", "content-length": "0"} }

2026-01-23T00:40:57.341051Z ERROR qdrant::actix::helpers: Error processing request: Service internal error: 2 of 2 read operations failed:

  Service internal error: Internal error: status: Internal, message: "Service internal error: task 1935219 panicked with message \"capacity overflow\"", details: [], metadata: MetadataMap { headers: {"content-type": "application/grpc", "date": "Fri, 23 Jan 2026 00:40:57 GMT", "content-length": "0"} }

  Service internal error: Internal error: status: Internal, message: "Service internal error: task 1959637 panicked with message \"capacity overflow\"", details: [], metadata: MetadataMap { headers: {"content-type": "application/grpc", "date": "Fri, 23 Jan 2026 00:40:56 GMT", "content-length": "0"} }

2026-01-23T00:40:57.341263Z  INFO actix_web::middleware::logger: 192.16.64.195 "POST /collections/a/points/query HTTP/1.1" 500 284 "-" "python-client/1.16.2 python/3.11.14" 0.380078

2026-01-23T00:40:57.346159Z DEBUG reqwest::connect: starting new connection: https://telemetry.qdrant.io/

2026-01-23T00:40:57.346465Z DEBUG reqwest::connect: starting new connection: https://telemetry.qdrant.io/

2026-01-23T00:40:57.346725Z DEBUG reqwest::connect: starting new connection: https://telemetry.qdrant.io/

2026-01-23T00:40:57.347507Z DEBUG reqwest::connect: starting new connection: https://telemetry.qdrant.io/

2026-01-23T00:40:57.347532Z DEBUG reqwest::connect: starting new connection: https://telemetry.qdrant.io/

2026-01-23T00:40:57.347583Z DEBUG reqwest::connect: starting new connection: https://telemetry.qdrant.io/

2026-01-23T00:40:57.348568Z ERROR qdrant::tonic::logging: gRPC /qdrant.PointsInternal/QueryBatch unexpectedly failed with Internal error "Service internal error: task 2249584 panicked with message \"capacity overflow\"" 0.101884

2026-01-23T00:40:57.349753Z DEBUG reqwest::connect: starting new connection: https://telemetry.qdrant.io/

2026-01-23T00:40:57.350014Z DEBUG reqwest::connect: starting new connection: https://telemetry.qdrant.io/

2026-01-23T00:40:57.355591Z DEBUG collection::shards::replica_set::execute_read_operation: Read operation failed: Service internal error: Internal error: status: Internal, message: "Service internal error: task 1959648 panicked with message \"capacity overflow\"", details: [], metadata: MetadataMap { headers: {"content-type": "application/grpc", "date": "Fri, 23 Jan 2026 00:40:56 GMT", "content-length": "0"} }

2026-01-23T00:40:57.355869Z ERROR qdrant::actix::helpers: Error processing request: Service internal error: 2 of 2 read operations failed:

  Service internal error: Internal error: status: Internal, message: "Service internal error: task 1935211 panicked with message \"capacity overflow\"", details: [], metadata: MetadataMap { headers: {"content-type": "application/grpc", "date": "Fri, 23 Jan 2026 00:40:57 GMT", "content-length": "0"} }

  Service internal error: Internal error: status: Internal, message: "Service internal error: task 1959648 panicked with message \"capacity overflow\"", details: [], metadata: MetadataMap { headers: {"content-type": "application/grpc", "date": "Fri, 23 Jan 2026 00:40:56 GMT", "content-length": "0"} }

2026-01-23T00:40:57.356385Z  INFO actix_web::middleware::logger: 192.16.64.195 "POST /collections/a/points/query HTTP/1.1" 500 285 "-" "python-client/1.16.2 python/3.11.14" 0.394645

2026-01-23T00:40:57.357733Z ERROR qdrant::tonic::logging: gRPC /qdrant.PointsInternal/QueryBatch unexpectedly failed with Internal error "Service internal error: task 2249635 panicked with message \"capacity overflow\"" 0.088083

2026-01-23T00:40:57.380472Z DEBUG collection::shards::replica_set::execute_read_operation: Read operation failed: Service internal error: Internal error: status: Internal, message: "Service internal error: task 1935533 panicked with message \"capacity overflow\"", details: [], metadata: MetadataMap { headers: {"content-type": "application/grpc", "date": "Fri, 23 Jan 2026 00:40:57 GMT", "content-length": "0"} }

2026-01-23T00:40:57.411441Z ERROR qdrant::tonic::logging: gRPC /qdrant.PointsInternal/QueryBatch unexpectedly failed with Internal error "Service internal error: task 2249735 panicked with message \"capacity overflow\"" 0.095241

2026-01-23T00:40:57.428309Z ERROR qdrant::tonic::logging: gRPC /qdrant.PointsInternal/QueryBatch unexpectedly failed with Internal error "Service internal error: task 2249808 panicked with message \"capacity overflow\"" 0.092861

2026-01-23T00:40:57.464077Z DEBUG collection::shards::replica_set::execute_read_operation: Read operation failed: Service internal error: Internal error: status: Internal, message: "Service internal error: task 1935777 panicked with message \"capacity overflow\"", details: [], metadata: MetadataMap { headers: {"content-type": "application/grpc", "date": "Fri, 23 Jan 2026 00:40:57 GMT", "content-length": "0"} }

2026-01-23T00:40:57.464307Z ERROR qdrant::actix::helpers: Error processing request: Service internal error: 2 of 2 read operations failed:

  Service internal error: task 2249144 panicked with message "capacity overflow"

  Service internal error: Internal error: status: Internal, message: "Service internal error: task 1935777 panicked with message \"capacity overflow\"", details: [], metadata: MetadataMap { headers: {"content-type": "application/grpc", "date": "Fri, 23 Jan 2026 00:40:57 GMT", "content-length": "0"} }

2026-01-23T00:40:57.464445Z  INFO actix_web::middleware::logger: 192.16.64.195 "POST /collections/b/points/query HTTP/1.1" 500 286 "-" "python-client/1.16.2 python/3.11.14" 0.391979

2026-01-23T00:44:09.980677Z  INFO actix_web::middleware::logger: 192.16.64.195 "GET /collections/a/exists HTTP/1.1" 200 68 "-" "python-client/1.16.2 python/3.11.14" 0.000803

2026-01-23T00:44:09.980847Z  INFO actix_web::middleware::logger: 192.16.64.195 "GET /collections/c/exists HTTP/1.1" 200 65 "-" "python-client/1.16.2 python/3.11.14" 0.000483

memory allocation of 4652464731773040 bytes failed

./entrypoint.sh: line 25:     6 Aborted

## Steps to Reproduce
```
def build_qdrant_filter(keywords, filters, logical_filtering):
    try:
        must_conditions = []
        should_conditions = []
        if keywords is not None:
            is_product_query = bool(keywords.get("product_names"))
            is_product_version_query = bool(keywords.get("product_versions"))
            is_document_type_query = bool(keywords.get("possible_document_types_for_the_answer"))

            if is_product_query:
                product_name_conditions = [
                    FieldCondition(key="metadata.file_metadata.product_names", match=MatchValue(value=keyword))
                    for keyword in keywords["product_names"] # normalize
                ]

                must_conditions.append(
                    Filter(
                        min_should=MinShould(
                            conditions = product_name_conditions,
                            min_count=1
                        )
                    )
                )

            if is_product_version_query:
                product_version_conditions = [
                    FieldCondition(key="metadata.file_metadata.product_versions", match=MatchValue(value=keyword))
                    for keyword in keywords["product_versions"] # normalize
                ]

                must_conditions.append(
                    Filter(
                        min_should=MinShould(
                            conditions = product_version_conditions,
                            min_count=1
                        )
                    )
                )
            
            if is_document_type_query:
                document_type_conditions = [
                    FieldCondition(key="metadata.file_metadata.document_type", match=MatchValue(value=keyword))
                    for keyword in keywords["possible_document_types_for_the_answer"] 
                ]

                must_conditions.append(
                    Filter(
                        min_should=MinShould(
                            conditions = document_type_conditions,
                            min_count=1
                        )
                    )
                )

            intent_terms = sorted(set(keywords.get("keywords", [])))
            min_should_count = min(
                len(intent_terms),
                max(2, len(intent_terms) // 3)
            ) if intent_terms else 1

            if intent_terms:
                summary_conditions = [
                    FieldCondition(
                        key="metadata.file_metadata.summary",
                        match=MatchText(text=keyword),
                    )
                    for keyword in intent_terms
                ]
                summary_filter = Filter(
                    min_should=MinShould(
                        conditions = summary_conditions,
                        min_count=min_should_count
                    )
                )

                keyword_conditions = [
                    FieldCondition(
                        key="metadata.file_metadata.keywords",
                        match=MatchText(text=keyword),
                    )
                    for keyword in intent_terms
                ]
                keywords_filter = Filter(
                    min_should=MinShould(
                        conditions = keyword_conditions,
                        min_count=min_should_count
                    )
                )

                must_conditions.append(Filter(
                    min_should=MinShould(
                        conditions=[summary_filter, keywords_filter],
                        min_count=1
                    )
                ))
        

        if filters is not None:
            if logical_filtering == "and":
                must_conditions += [
                    FieldCondition(key=f"metadata.file_metadata.{k}", match=MatchText(text=str(v)))
                    for k, v in filters.items()
                ]
            elif logical_filtering == "or":
                should_conditions += [
                    FieldCondition(key=f"metadata.file_metadata.{k}", match=MatchText(text=str(v)))
                    for k, v in filters.items()
                ]
        len_keywords = len(keywords) if keywords else 0
        logger.info(f"Length of keywords {keywords} - {len_keywords}")

        builded_filter = Filter(
            must=must_conditions if must_conditions else None,
            should=should_conditions if should_conditions else None,
        )
        return builded_filter
    except Exception as e:
        current_time = datetime.now().strftime('%Y-%m-%d %H:%M:%S')
        logger.error(f"{current_time}  log message: RAG FAILED - Some error occured during building qdrant filter: {str(e)}.") 

dynamically_builded_filter = build_qdrant_filter(keywords, filters, logical_filtering)
                    limit = 12
                    return await qdrant_client.query_points(
                        collection_name=collection_name,
                        prefetch=[
                            Prefetch(
                                query=SparseVector(indices=sparse['indices'], values=sparse['values']),
                                using="sparse",
                                limit=limit,
                            ),
                            Prefetch(
                                query=dense_vec,
                                using="dense",
                                limit=limit,
                            ),
                        ],
                        query=FusionQuery(fusion=Fusion.RRF),
                        query_filter = dynamically_builded_filter,
                        limit=limit
                    )
```

## Expected Behavior
Query functions are working before upgrade without issues

## Context (Environment)
server: 1.16.3
python client: 1.16.2

Config: 
```
        "vectors": {

            "dense": {

                "size": 1024,

                "distance": "Dot",

                "on_disk": true 

            }

        },

        "shard_number": 3,

        "replication_factor": 2,

        "write_consistency_factor": 1,

        "on_disk_payload": true,

        "sparse_vectors": {

            "sparse": {

                "modifier": "idf"

            }

    },

    "hnsw_config": {

        "m": 16,

        "ef_construct": 100,

        "full_scan_threshold": 10000,

        "max_indexing_threads": 1, 

        "on_disk": true           

    },

    "optimizer_config": {

        "deleted_threshold": 0.2,

        "vacuum_min_vector_number": 1000,

        "default_segment_number": 0,

        "max_segment_size": null,

        "memmap_threshold": 10000,  

        "indexing_threshold": 20000,

        "flush_interval_sec": 10,   

        "max_optimization_threads": 1

    },

    "wal_config": {

        "wal_capacity_mb": 32,

        "wal_segments_ahead": 0

    },

    "quantization_config": {

        "scalar": {

            "type": "int8",

            "always_ram": true      

        }

    }

}'

 
```

## Detailed Description
Restart with Panic
Restart with OOMKilled Error

Image

Image

### PR DESCRIPTION
**Pull request by krapcys1-maker**
Fixes #7974

### Summary
This PR prevents a panic (`alloc::raw_vec::capacity_overflow`) in
`segment::index::query_estimator::combine_min_should_estimations` when
`min_should.min_count` is an edge value.

### What changed
- Add guards in `combine_min_should_estimations`:
  - `min_count == 0` → `CardinalityEstimation::exact(total)` (trivially satisfied)
  - `min_count > estimations.len()` → `CardinalityEstimation::exact(0)` (unsatisfiable)
- Add 2 regression unit tests covering both cases.

### Why
Without these guards, malformed/edge inputs can reach `combinations(min_count)` and
trigger pathological allocation, leading to a server panic instead of a safe estimate.

### Local verification
`cargo test -p segment` ✅

### All Submissions:

* [x] Contributions should target the `dev` branch. Did you create your branch from `dev`?
* [x] Have you followed the guidelines in our Contributing document?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?

### New Feature Submissions:

1. [ ] Does your submission pass tests?
2. [ ] Have you formatted your code locally using `cargo +nightly fmt --all` command prior to submission?
3. [ ] Have you checked your code using `cargo clippy --workspace --all-features` command?

### Changes to Core Features:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new tests for your core changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?

### CODE REVIEW

File: lib/segment/src/index/query_estimator.rs [hunk 1]
```diff
@@ -114,6 +114,18 @@ pub fn combine_min_should_estimations(
...
+    // - min_count == 0  => trivially satisfied for all points
+    // - min_count > N   => unsatisfiable
+    //
+    // Also prevents pathological allocation paths in combinations(min_count).
+    if min_count == 0 {
+        return CardinalityEstimation::exact(total);
+    }
+    if min_count > estimations.len() {
+        return CardinalityEstimation::exact(0);
+    }
```
Comment (coszio) [inline lib/segment/src/index/query_estimator.rs]: The current implementation already estimates nicely, but it is not protected against overallocation. Perhaps a simpler fix would be to:
```suggestion
    // Prevent pathological allocation paths in combinations(min_count).
    if min_count > estimations.len() {
        return CardinalityEstimation::exact(0);
    }
```

Comment (krapcys1-maker) [reply lib/segment/src/index/query_estimator.rs]: Good point, thanks for the suggestion.

You're right — the estimator already handles `min_count == 0` correctly.
I've simplified the patch to only guard against `min_count > estimations.len()` to prevent pathological allocation.

Updated accordingly.

**Review by generall — APPROVED** [review]
