### PR TITLE
Fix `GraphLinksConverter::serialize_to` data alignment issues

### LINKED ISSUE #3802: Unsafe usage of `std::slice::from_raw_parts`
`segment::common::mmap_ops::transmute_from_u8_to_slice` and `segment::common::mmap_ops::transmute_from_u8_to_mut_slice` ([link](https://github.com/qdrant/qdrant/blob/3fbe1cae6cb7f51a0c5bb4b45cfe6749ac76ed59/lib/common/memory/src/mmap_ops.rs#L106-L118)) call `std::slice::from_raw_parts` with `&[u8]` slice whose start is potentially unaligned for a slice of `&[T]`.

We've observed panics in `segment::index::hnsw_index::graph_links::GraphLinksConverter::serialize_to` — the panic comes from the [precondition assertion in the standard library](https://doc.rust-lang.org/src/core/slice/raw.rs.html#97).

We only observed this when updating from the `nightly-2023-11-01` toolchain to `nightly-2024-03-05`, though the panic also reproduced on various toolchains in between. I believe the issue is still present on older toolchains, but the precondition check was altered slightly in between to make it detect this case. I believe the code is potentially invoking undefined behavior regardless, as the pointer is never guaranteed to be aligned here.

In the specific case of `GraphLinksConverter::serialize_to`, it's relatively easy to fix — the transmuted slice is only used for the convenience of serializing a `&[T]` into a `&[u8]` mmap slice. I have a patch prepared that removes the undefined behavior from this function by transmuting `&[T]` into `&[u8]` and copying that transmuted slice into the `&[u8]` mmap, rather than trying to do the opposite.

However, there are many other usages of these `transmte_from_u8_*` methods throughout the `segment` crate that are vulnerable to the same issue.

## Current Behavior
Panics in `std::slice::from_raw_parts` caused by `GraphLinksConverter::serialize_to`.

<details>
<summary>Backtrace</summary>

```
thread '<unnamed>' panicked at library/core/src/panicking.rs:155:5:
unsafe precondition(s) violated: slice::from_raw_parts_mut requires the pointer to be aligned and non-null, and the total size of the slice not to exceed `isize::MAX`
stack backtrace:
   0:        0x107f100e0 - std::backtrace_rs::backtrace::libunwind::trace::he983ffd396d11726
                               at /rustc/d18480b84fdbf1efc34f62070951334aa833d761/library/std/src/../../backtrace/src/backtrace/libunwind.rs:104:5
   1:        0x107f100e0 - std::backtrace_rs::backtrace::trace_unsynchronized::h6002dff5d78caefc
                               at /rustc/d18480b84fdbf1efc34f62070951334aa833d761/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:        0x107f100e0 - std::sys_common::backtrace::_print_fmt::hb1166eaef5f787e8
                               at /rustc/d18480b84fdbf1efc34f62070951334aa833d761/library/std/src/sys_common/backtrace.rs:68:5
   3:        0x107f100e0 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hba72210463b198ae
                               at /rustc/d18480b84fdbf1efc34f62070951334aa833d761/library/std/src/sys_common/backtrace.rs:44:22
   4:        0x107f34c48 - core::fmt::rt::Argument::fmt::h8efe6a884a6b4a7c
                               at /rustc/d18480b84fdbf1efc34f62070951334aa833d761/library/core/src/fmt/rt.rs:142:9
   5:        0x107f34c48 - core::fmt::write::h4cb8d55c8d85b829
                               at /rustc/d18480b84fdbf1efc34f62070951334aa833d761/library/core/src/fmt/mod.rs:1120:17
   6:        0x107f0c1ac - std::io::Write::write_fmt::h650fcc3e985a9260
                               at /rustc/d18480b84fdbf1efc34f62070951334aa833d761/library/std/src/io/mod.rs:1846:15
   7:        0x107f0ff20 - std::sys_common::backtrace::_print::h1c7c6a43a3a6a7f9
                               at /rustc/d18480b84fdbf1efc34f62070951334aa833d761/library/std/src/sys_common/backtrace.rs:47:5
   8:        0x107f0ff20 - std::sys_common::backtrace::print::h70c88364c7e47672
                               at /rustc/d18480b84fdbf1efc34f62070951334aa833d761/library/std/src/sys_common/backtrace.rs:34:9
   9:        0x107f118a0 - std::panicking::default_hook::{{closure}}::h91c4e952f264ae22
  10:        0x107f11584 - std::panicking::default_hook::h0a763560f5583a48
                               at /rustc/d18480b84fdbf1efc34f62070951334aa833d761/library/std/src/panicking.rs:292:9
  11:        0x105556180 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h9430742de71445fa
                               at /rustc/d18480b84fdbf1efc34f62070951334aa833d761/library/alloc/src/boxed.rs:2030:9
  12:        0x105556180 - test::test_main::{{closure}}::heea6bc9506ea3095
                               at /rustc/d18480b84fdbf1efc34f62070951334aa833d761/library/test/src/lib.rs:138:21
  13:        0x107f121c0 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h05d1fb7a322042c3
                               at /rustc/d18480b84fdbf1efc34f62070951334aa833d761/library/alloc/src/boxed.rs:2030:9
  14:        0x107f121c0 - std::panicking::rust_panic_with_hook::h4add6ff44d6506d6
                               at /rustc/d18480b84fdbf1efc34f62070951334aa833d761/library/std/src/panicking.rs:783:13
  15:        0x107f11b54 - std::panicking::begin_panic_handler::{{closure}}::h6b17d83e3f43c72e
                               at /rustc/d18480b84fdbf1efc34f62070951334aa833d761/library/std/src/panicking.rs:649:13
  16:        0x107f1056c - std::sys_common::backtrace::__rust_end_short_backtrace::he502a3b814db59f8
                               at /rustc/d18480b84fdbf1efc34f62070951334aa833d761/library/std/src/sys_common/backtrace.rs:171:18
  17:        0x107f118f8 - rust_begin_unwind
                               at /rustc/d18480b84fdbf1efc34f62070951334aa833d761/library/std/src/panicking.rs:645:5
  18:        0x107f9d628 - core::panicking::panic_nounwind_fmt::runtime::h9b5cd9f9717fd71c
                               at /rustc/d18480b84fdbf1efc34f62070951334aa833d761/library/core/src/panicking.rs:110:18
  19:        0x107f9d628 - core::panicking::panic_nounwind_fmt::hdf68d2e4a50cf423
                               at /rustc/d18480b84fdbf1efc34f62070951334aa833d761/library/core/src/panicking.rs:122:9
  20:        0x107f9d6a8 - core::panicking::panic_nounwind::hfc32d53c3917613d
                               at /rustc/d18480b84fdbf1efc34f62070951334aa833d761/library/core/src/panicking.rs:155:5
  21:        0x105ebbf58 - core::slice::raw::from_raw_parts_mut::precondition_check::h9514179f7a9eac5a
                               at /rustc/d18480b84fdbf1efc34f62070951334aa833d761/library/core/src/intrinsics.rs:2752:21
  22:        0x105ebbe30 - core::slice::raw::from_raw_parts_mut::h803966888de7facf
                               at /rustc/d18480b84fdbf1efc34f62070951334aa833d761/library/core/src/slice/raw.rs:151:9
  23:        0x105d748d8 - segment::common::mmap_ops::transmute_from_u8_to_mut_slice::hfedc79407c28d87d
                               at /Users/gautam/.cargo/git/checkouts/qdrant-8737e58dc64e4125/76482c6/lib/segment/src/common/mmap_ops.rs:111:14
  24:        0x105f1c150 - segment::index::hnsw_index::graph_links::GraphLinksConverter::serialize_to::had09a0accc44d1f3
                               at /Users/gautam/.cargo/git/checkouts/qdrant-8737e58dc64e4125/76482c6/lib/segment/src/index/hnsw_index/graph_links.rs:237:44
  25:        0x105f1c8a0 - segment::index::hnsw_index::graph_links::GraphLinksConverter::save_as::h680d395a2df29d7a
                               at /Users/gautam/.cargo/git/checkouts/qdrant-8737e58dc64e4125/76482c6/lib/segment/src/index/hnsw_index/graph_links.rs:283:13
  26:        0x105d828f8 - segment::index::hnsw_index::graph_layers_builder::GraphLayersBuilder::into_graph_layers::ha7cfddb3345993af
                               at /Users/gautam/.cargo/git/checkouts/qdrant-8737e58dc64e4125/76482c6/lib/segment/src/index/hnsw_index/graph_layers_builder.rs:88:13
  27:        0x105d2ca78 - <segment::index::hnsw_index::hnsw::HNSWIndex<TGraphLinks> as segment::index::vector_index_base::VectorIndex>::build_index::h2bf2d242ebad7627
                               at /Users/gautam/.cargo/git/checkouts/qdrant-8737e58dc64e4125/76482c6/lib/segment/src/index/hnsw_index/hnsw.rs:637:27
  28:        0x105d89a78 - <segment::index::vector_index_base::VectorIndexEnum as segment::index::vector_index_base::VectorIndex>::build_index::hcee4f9abaf31ca0d
                               at /Users/gautam/.cargo/git/checkouts/qdrant-8737e58dc64e4125/76482c6/lib/segment/src/index/vector_index_base.rs:76:49
  29:        0x105f23c78 - segment::segment_constructor::segment_builder::SegmentBuilder::build::h5e8883e19c35bd52
                               at /Users/gautam/.cargo/git/checkouts/qdrant-8737e58dc64e4125/76482c6/lib/segment/src/segment_constructor/segment_builder.rs:198:17
  30:        0x105b905e4 - vector::qdrant_segments::merge_disk_segments::h08051a9f23100bd0
[snipped, closed-source frames follow]
```

</details>

## Expected Behavior
`std::slice::from_raw_parts` should never be called on an unaligned pointer / should not panic.

## Possible Solution
I can add a patch that would fix the issue for `GraphLinks::serialize_to` specifically, but would not fix all usages of this across the code base. It'd depend on how the transmuted slice is actually needed.

### PR DESCRIPTION
**Pull request by ffuugoo**
This PR fix data alignment issue in `GraphLinksConverter::serialize_to` that was discovered in #3802.

It also adds a few asserts to the `transmute_from_u8*` functions, to try to catch similar alignment mismatches in the future.

Fixes #3802. Includes #3807.

### All Submissions:

* [x] Contributions should target the `dev` branch. Did you create your branch from `dev`?
* [x] Have you followed the guidelines in our Contributing document?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?

### New Feature Submissions:

1. [x] Does your submission pass tests?
2. [x] Have you formatted your code locally using `cargo +nightly fmt --all` command prior to submission?
3. [x] Have you checked your code using `cargo clippy --all --all-features` command?

### Changes to Core Features:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your core changes, as applicable?
* [ ] Have you successfully ran tests with your changes locally?

### CODE REVIEW

**Comment by ffuugoo** [comment]
@generall @timvisee @IvanPleshkov I think this asserts *should* catch alignment mismatches in our code? Let's see if it will break any tests.

**Comment by IvanPleshkov** [comment]
@ffuugoo Do you know how to easily fix storage compatibility test? It passes but logs are full of errors. Log snippet:
```
2024-03-11T13:45:16.587922Z ERROR qdrant::startup: Panic occurred in file /home/runner/work/qdrant/qdrant/lib/common/memory/src/mmap_ops.rs at line 122: assertion `left == right` failed: transmuting byte slice 0x0x7f3143d0cbe4 into slice of u64: required alignment is 8 bytes, byte slice misaligned by 4 bytes
  left: 4
 right: 0    
2024-03-11T13:45:16.589293Z DEBUG reqwest::connect: starting new connection: https://staging-telemetry.qdrant.io/    
2024-03-11T13:45:16.981934Z ERROR collection::shards::replica_set: Failed to load local shard "./storage/collections/test_collection/0", initializing "dummy" shard instead: Service internal error: Can't join segment load thread: TypeId { t: 42966343538335219590177265727833432740 }    
```

**Review by timvisee — COMMENTED** [review]
:+1:

**Comment by ffuugoo** [comment]
> Do you know how to easily fix storage compatibility test?

Do you mean, "how to make these tests fail, instead of passing with a dummy"? If so, not sure.

This PR (so far) mostly to show that we *do* have (mis)alignment issues and that they are easy to reproduce. The best fix would be to fix the alignment issues in the first place.

File: lib/segment/src/index/hnsw_index/graph_links.rs [hunk 1]
```diff
@@ -224,9 +255,10 @@ impl GraphLinksConverter {
             let links_range = header.get_links_range();
             let offsets_range = header.get_offsets_range();
             let union_range = links_range.start..offsets_range.end;
-            let (links_mmap, offsets_mmap) = bytes_data[union_range]
+            let (links_mmap, offsets_with_padding_mmap) = bytes_data[union_range]
                 .as_mut()
                 .split_at_mut(links_range.len());
+            let offsets_mmap = &mut offsets_with_padding_mmap[header.offsets_padding as _..];
```
Comment (ffuugoo) [inline lib/segment/src/index/hnsw_index/graph_links.rs:261]: I've tweaked @IvanPleshkov's code here, to make sure `offsets_padding` betes *aren't* included as (an invalid) last element of `links_mmap`.

But, please, check my slicing here....

**Comment by ffuugoo** [comment]
Thanks @IvanPleshkov for fixing the alignment issues in `GraphLinks*`!

I've updated the PR description, switched alignment asserts back to `debug_assert` and added a small fix. It's ready for the final review, I think.

File: lib/segment/src/index/hnsw_index/graph_links.rs (hunk 1 above)
Comment (IvanPleshkov) [reply lib/segment/src/index/hnsw_index/graph_links.rs:261]: > I've tweaked @IvanPleshkov's code here, to make sure `offsets_padding` betes _aren't_ included as (an invalid) last element of `links_mmap`. (See [this comment](https://github.com/qdrant/qdrant/pull/3807#discussion_r1521806532) from #3807.)
> 
> But, please, check my slicing here....

Thanks for the fix, you are totally right and I like your opinion!

**Review by IvanPleshkov — APPROVED** [review]

**Comment by agourlay** [comment]
Maybe we could merge first https://github.com/qdrant/qdrant/pull/3816 and rebase.
It introduces more coverage for mmap configurations.

**Comment by agourlay** [comment]
Merged, please rebase :gear:

**Review by generall — APPROVED** [review]
