### PR TITLE
fix(rest): expose HTTP transport timeout controls for persistent clients

### LINKED ISSUE #6481: httpx.RemoteProtocolError: Server disconnected without sending a response
## Current Behavior
While performing concurrent ingestion using the Qdrant Python client (HTTP mode, httpx==0.27.2), I consistently encounter the following error:

`httpx.RemoteProtocolError: Server disconnected without sending a response
`

This happens even with very small batch sizes (15 points) and a semaphore-limited maximum of 5 concurrent ingestion threads.

## Steps to Reproduce

1. Using Qdrant in Docker (`image:v1.13.4`)
2. Ingesting ~15 points per batch using `qdrant_client.upsert(...)`

Ingestion function is attached below:

 ```
 ` # Prepare points for embeddings based on mode
              for i, doc in enumerate(documents):
                  # Create point structure with common fields
                  point = PointStruct(
                      id=str(uuid.uuid4()),
                      vector={
                          dense_vector_name: dense_embeddings[i],
                          sparse_vector_name: sparse_embeddings[i],
                      },
                      payload={
                          "page_content": doc.page_content,
                          "metadata": doc.metadata
                      }
                  )
                  points.append(point)
                  
              logger.debug(f"Size of points to be stored in collection {collection_name} is {len(points)}")
              # Upload all embeddings at once
              if semaphore:
                  with semaphore:
                      self.qdrant_client.upsert(
                          collection_name=collection_name,
                          points=points,
                          wait=False
                      )
              else:
                  self.qdrant_client.upsert(
                      collection_name=collection_name,
                      points=points,
                      wait=False
                  )
              logger.info(f"Successfully added {len(documents)} splits to the collection {collection_name} in the qdrant vector database.")`
```

3. Both dense and sparse vectors are used per point
4. Upsert is called inside a function wrapped in a `Semaphore(5)` (tried 3 also) to limit concurrency. I have also tried it without `semaphore` but issue persists.

5. ` wait=False `or `wait=True` both tested — issue persists

6. HTTP client is` httpx==0.27.2`

## Expected Behavior

Qdrant should either:

Respond with an error (e.g., 503 Service Unavailable, memory limit exceeded), or

Continue to handle small batch ingestion under moderate concurrency without dropping connections unexpectedly

## Context (Environment)

Qdrant version: latest (Docker image)

Qdrant client version: `qdrant-client==1.8.0
`
`httpx version: 0.27.2
`
`Python: 3.11`

Platform: Ubuntu 22.04, running in AWS EC2

Running inside Docker: Yes

Number of parallel ingestion threads: 5 (semaphore-limited)

Batch size: 15 points

Each point includes: dense (768d) + sparse embeddings + metadata

## Detailed Description

The ingestion runs successfully for a number of batches, then randomly fails with:
```
ERROR - Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/new_cdr/lib/python3.11/site-packages/httpx/_transports/default.py", line 72, in map_httpcore_exceptions
    yield
  File "/home/ubuntu/miniconda3/envs/new_cdr/lib/python3.11/site-packages/httpx/_transports/default.py", line 236, in handle_request
    resp = self._pool.handle_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/miniconda3/envs/new_cdr/lib/python3.11/site-packages/httpcore/_sync/connection_pool.py", line 256, in handle_request
    raise exc from None
  File "/home/ubuntu/miniconda3/envs/new_cdr/lib/python3.11/site-packages/httpcore/_sync/connection_pool.py", line 236, in handle_request
    response = connection.handle_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/miniconda3/envs/new_cdr/lib/python3.11/site-packages/httpcore/_sync/connection.py", line 103, in handle_request
    return self._connection.handle_request(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/miniconda3/envs/new_cdr/lib/python3.11/site-packages/httpcore/_sync/http11.py", line 136, in handle_request
    raise exc
  File "/home/ubuntu/miniconda3/envs/new_cdr/lib/python3.11/site-packages/httpcore/_sync/http11.py", line 106, in handle_request
    ) = self._receive_response_headers(**kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/miniconda3/envs/new_cdr/lib/python3.11/site-packages/httpcore/_sync/http11.py", line 177, in _receive_response_headers
    event = self._receive_event(timeout=timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/miniconda3/envs/new_cdr/lib/python3.11/site-packages/httpcore/_sync/http11.py", line 231, in _receive_event
    raise RemoteProtocolError(msg)
httpcore.RemoteProtocolError: Server disconnected without sending a response.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/new_cdr/lib/python3.11/site-packages/qdrant_client/http/api_client.py", line 116, in send_inner
    response = self._client.send(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/miniconda3/envs/new_cdr/lib/python3.11/site-packages/httpx/_client.py", line 926, in send
    response = self._send_handling_auth(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/miniconda3/envs/new_cdr/lib/python3.11/site-packages/httpx/_client.py", line 954, in _send_handling_auth
    response = self._send_handling_redirects(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/miniconda3/envs/new_cdr/lib/python3.11/site-packages/httpx/_client.py", line 991, in _send_handling_redirects
    response = self._send_single_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/miniconda3/envs/new_cdr/lib/python3.11/site-packages/httpx/_client.py", line 1027, in _send_single_request
    response = transport.handle_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/miniconda3/envs/new_cdr/lib/python3.11/site-packages/httpx/_transports/default.py", line 235, in handle_request
    with map_httpcore_exceptions():
  File "/home/ubuntu/miniconda3/envs/new_cdr/lib/python3.11/contextlib.py", line 158, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/home/ubuntu/miniconda3/envs/new_cdr/lib/python3.11/site-packages/httpx/_transports/default.py", line 89, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.RemoteProtocolError: Server disconnected without sending a response.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/actransit-cdr/corporate-data-repository/app/vectorization/vector_store/qdrant_vector_store.py", line 165, in create_vector_store
    self.qdrant_client.upsert(
  File "/home/ubuntu/miniconda3/envs/new_cdr/lib/python3.11/site-packages/qdrant_client/qdrant_client.py", line 1567, in upsert
    return self._client.upsert(
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/miniconda3/envs/new_cdr/lib/python3.11/site-packages/qdrant_client/qdrant_remote.py", line 1908, in upsert
    http_result = self.openapi_client.points_api.upsert_points(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/miniconda3/envs/new_cdr/lib/python3.11/site-packages/qdrant_client/http/api/points_api.py", line 987, in upsert_points
    return self._build_for_upsert_points(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/miniconda3/envs/new_cdr/lib/python3.11/site-packages/qdrant_client/http/api/points_api.py", line 512, in _build_for_upsert_points
    return self.api_client.request(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/miniconda3/envs/new_cdr/lib/python3.11/site-packages/qdrant_client/http/api_client.py", line 89, in request
    return self.send(request, type_)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/miniconda3/envs/new_cdr/lib/python3.11/site-packages/qdrant_client/http/api_client.py", line 106, in send
    response = self.middleware(request, self.send_inner)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/miniconda3/envs/new_cdr/lib/python3.11/site-packages/qdrant_client/http/api_client.py", line 215, in __call__
    return call_next(request)
           ^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/miniconda3/envs/new_cdr/lib/python3.11/site-packages/qdrant_client/http/api_client.py", line 118, in send_inner
    raise ResponseHandlingException(e)
qdrant_client.http.exceptions.ResponseHandlingException: Server disconnected without sending a response.
```

### PR DESCRIPTION
**Pull request by krapcys1-maker**
Fixes #6481

## Summary

This PR exposes REST transport timeout controls to reduce sporadic client-side
`RemoteProtocolError: Server disconnected without sending a response` in persistent HTTP client scenarios.

### What changed

- Added new `service` config fields:
  - `http_keep_alive_timeout_sec` (default: `75`)
  - `http_client_request_timeout_sec` (default: `30`)
  - `http_client_disconnect_timeout_sec` (default: `30`)
- Wired these fields into Actix `HttpServer` setup:
  - `.keep_alive(...)`
  - `.client_request_timeout(...)`
  - `.client_disconnect_timeout(...)`
- Added startup log line with effective REST transport values.
- Updated `config/config.yaml` with new keys and operational comments.

### Why

Issue reports indicate that increasing request timeout alone was not enough.
This points to connection lifecycle behavior (keep-alive / transport timeouts),
not only operation timeout. This patch makes transport behavior explicit and tunable.
## Compatibility

- Fully backward compatible.
- Defaults preserve current behavior.
- No breaking API changes.

## Operational impact

Operators can now tune HTTP transport lifecycle behavior
without recompiling or modifying server code.

### All Submissions:

- [x] Target branch: dev
- [x] Tests passing
- [x] Clippy clean

### CODE REVIEW

File: src/settings.rs [hunk 1]
```diff
@@ -404,6 +416,18 @@ const fn default_cors() -> bool {
...
+    75
+}
+
+const fn default_http_client_request_timeout_sec() -> u64 {
+    30
+}
+
+const fn default_http_client_disconnect_timeout_sec() -> u64 {
+    30
+}
```
Comment (timvisee) [inline src/settings.rs:429]: Where are these values coming from? Documentation states different defaults:

- [`keep_alive`](https://docs.rs/actix-web/latest/actix_web/struct.HttpServer.html#method.keep_alive): 5s
- [`client_request_timeout`](https://docs.rs/actix-web/latest/actix_web/struct.HttpServer.html#method.client_request_timeout): 5s
- [`client_disconnect_timeout`](https://docs.rs/actix-web/latest/actix_web/struct.HttpServer.html#method.client_disconnect_timeout): 5s

The values you suggest here might actually be better for our use case. But I'm just curious where they came from, as you mention we keep the existing settings.

Comment (krapcys1-maker) [reply src/settings.rs:429]: Good catch — thanks for pointing that out.

These values (75/30/30) are not from Actix defaults. I introduced them as operational defaults based on persistent-client behavior from #6481 and common client timeout ranges, but you’re right that this does not strictly preserve existing server defaults.

I’ll align defaults to Actix defaults to keep backward compatibility, and keep these knobs as explicit config overrides only. If helpful, I can also add a short note in config/docs with “recommended values for long-lived/pooling clients".

File: config/config.yaml [hunk 2]
```diff
@@ -246,6 +246,23 @@ service:
...
+  # to avoid premature request read timeouts.
+  # Trade-off: higher values reduce false timeouts, but keep worker resources busy longer.
+  http_client_request_timeout_sec: 5
+
+  # Timeout for waiting on client disconnect in seconds.
+  # Increase this for high-latency/lossy networks, long-lived client processing, or
+  # connection pooling setups where disconnect detection can be delayed.
+  # Trade-off: higher values reduce false disconnects, but tie up server resources longer.
+  http_client_disconnect_timeout_sec: 5
+
```
Comment (timvisee) [inline config/config.yaml]: I'd prefer to remove it from the configuration so that we don't bloat it too much. People can still add it manually or use environment variables to change the setting.

```suggestion
```

After that I'm happy to merge.

Comment (krapcys1-maker) [reply config/config.yaml]: agreed

I removed all three HTTP transport timeout keys from `config/config.yaml` to avoid bloating the default config, as suggested.

Behavior is unchanged:
- defaults are still defined in `ServiceConfig` (`src/settings.rs`) as 5s,
- users can still override via runtime config / environment variables.

I also re-ran the relevant tests:
- `cargo test test_custom_http_transport_config -- --nocapture`
- `cargo test test_invalid_http_transport_config -- --nocapture`

Both pass.

**Comment by krapcys1-maker** [comment]
Glad it helped 🙂
